# docker-compose.yml

version: '3.8'
services:

  # Docker connection string: postgres://postgres:postgres@localhost:5432/

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    # 容器主机名为minio
    hostname: redis-shop
    restart: always
    ports:
      - '6379:6379'
      # Define volumes


volumes:
  postgres:
  redis:
